### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Hiobi**
Hi,
some french in it. :3

### CODE REVIEW

**Comment by MichaelBelgium** [comment]
I appreciate the work but any specific reason why u're not adding it in the french language pack?

I'm not really a fan of having translations in extensions. Fits more if its in a language pack.

**Comment by Hiobi** [comment]
Hi,
I understand, I'm pretty with that.
But it seems that many others developpers prefer to add it to their own repository, not in the language pack. For example, in the french language there is only translation for core's extensions.

https://discuss.flarum.org/d/615-french-language-pack/200

**Comment by MichaelBelgium** [comment]
Mhm yeah everyone has his own preference ofcourse. But like in the [dutch language pack](https://github.com/MichaelBelgium/flarum-dutch) ive put my extensions.

But alright, ill merge it here then

**Comment by Hiobi** [comment]
Don’t worry Michael, do what you prefer, I can make PR on French language pack too.
It’s more easier.

Just for notice, now it seems that Reflar doesn’t want anymore to accept language’s files PR on their own repository, to prefer language pack.

I’m totally in line with this preference, it’s more easier for everyone. :)

I will make PR on French language pack! 
Thanks !

**Comment by MichaelBelgium** [comment]
Oooh, well i merged it now, so u don't really have to do. But okay sure, if that PR gets accepted i'll remove it here then

**Comment by Hiobi** [comment]
okay!  I'll let you know.

**Pull request merged**
